<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bioregionalization in Ecology using SCCA • SCCA</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Bioregionalization in Ecology using SCCA">
<meta property="og:description" content="This vignette walks readers through useful applications of package SCCA in the    field of ecology.
">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">SCCA</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.9.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/using_scca.html">Bioregionalization in Ecology using SCCA</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="using_scca_files/accessible-code-block-0.0.1/empty-anchor.js"></script><link href="using_scca_files/anchor-sections-1.0/anchor-sections.css" rel="stylesheet">
<script src="using_scca_files/anchor-sections-1.0/anchor-sections.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Bioregionalization in Ecology using SCCA</h1>
                        <h4 class="author">I. Morales-Castilla</h4>
            
            <h4 class="date">2021-02-25</h4>
      
      
      <div class="hidden name"><code>using_scca.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>This vignette walks readers through a useful application of the package SCCA in the field of ecology. Specifically, it does so using a case study for global carnivores, allowing to replicate the results in <a href="#van_dam">van Dam, et al</a>.</p>
<p>We will show how to perform Correspondence Analysis to an incidence (presence-absence) matrix representing the distribution of the global Carnivora, including both marine and terrestrial species. We demonstrate the most common functions to obtain bioregions and/or chorotypes and to visualize analytic results.</p>
</div>
<div id="installing-and-loading-the-package" class="section level2">
<h2 class="hasAnchor">
<a href="#installing-and-loading-the-package" class="anchor"></a>Installing and loading the package</h2>
<p>If not already been done, the package must be installed from GitHub:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## install and load packages</span>
<span class="co">#library(devtools)</span>
<span class="co">#install_github("UtrechtUniversity/SCCA", build_vignettes = TRUE)</span></code></pre></div>
<p>Assuming the package SCCA has been installed the package can now be loaded. <strong>Explanation why setting a seed? See also my remark </strong></p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">SCCA</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">0</span><span class="op">)</span></code></pre></div>
</div>
<div id="data-on-global-carnivora" class="section level2">
<h2 class="hasAnchor">
<a href="#data-on-global-carnivora" class="anchor"></a>Data on global Carnivora</h2>
<p>The package has a pre-loaded incidence matrix of presences-absences of global carnivores (Mammalia) from both land and oceans. The data set is downloaded from <a href="#faurby">DRYAD</a>. A quick glance to the data:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">carnivora</span><span class="op">)</span>
<span class="co">#&gt; [1] 41580   288</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">carnivora</span><span class="op">[</span><span class="fl">14000</span><span class="op">:</span><span class="fl">14006</span>, <span class="fl">150</span><span class="op">:</span><span class="fl">160</span><span class="op">]</span><span class="op">)</span>
<span class="co">#&gt;       149 150 151 152 153 154 155 156 157 158 159</span>
<span class="co">#&gt; 13999   0   0   0   0   0   0   0   0   1   0   1</span>
<span class="co">#&gt; 14000   0   0   0   0   0   0   0   0   1   0   1</span>
<span class="co">#&gt; 14001   0   0   0   0   0   0   0   0   1   0   1</span>
<span class="co">#&gt; 14002   0   0   1   0   0   0   0   0   1   0   1</span>
<span class="co">#&gt; 14003   0   0   1   0   0   0   0   0   1   0   1</span>
<span class="co">#&gt; 14004   0   0   1   0   0   0   0   0   1   0   1</span></code></pre></div>
<p>The data contains a binary matrix of sites x species (rows x columns) with values of 0 indicating absence and values of 1 indicating presence of a given species <em>j</em> in site <em>i</em>. Specifically, there are 41580 sites representing ca. 100 x 100 km grid cells distributed globally and with at least one presence. There are 288 species including marine and terrestrial carnivores.</p>
<p>We can have a look at the geographic distribution of those sites by loading the pre-loaded coordinates of the carnivora dataset, which are named <em>carnivora_sites</em>. Also, we can list which species are represented in each column with teh pre-loaded <em>carnivora_species</em>.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># retrieve coordinates</span>
<span class="va">sites</span> <span class="op">&lt;-</span> <span class="va">carnivora_sites</span>

<span class="co"># inspect </span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">sites</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 6 x 3</span>
<span class="co">#&gt;   site    lon   lat</span>
<span class="co">#&gt;   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;</span>
<span class="co">#&gt; 1 0     -179.  80.7</span>
<span class="co">#&gt; 2 1     -178.  80.7</span>
<span class="co">#&gt; 3 2     -177.  80.7</span>
<span class="co">#&gt; 4 3     -176.  80.7</span>
<span class="co">#&gt; # … with 2 more rows</span>

<span class="co"># retrieve species</span>
<span class="va">carnivores</span> <span class="op">&lt;-</span> <span class="va">carnivora_species</span>

<span class="co"># inspect </span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">carnivores</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 6 x 2</span>
<span class="co">#&gt;   species_id species_name                      </span>
<span class="co">#&gt;   &lt;chr&gt;      &lt;chr&gt;                             </span>
<span class="co">#&gt; 1 0          Acinonyx_jubatus_Terrestrial      </span>
<span class="co">#&gt; 2 1          Ailuropoda_melanoleuca_Terrestrial</span>
<span class="co">#&gt; 3 2          Ailurus_fulgens_Terrestrial       </span>
<span class="co">#&gt; 4 3          Aonyx_capensis_Terrestrial        </span>
<span class="co">#&gt; # … with 2 more rows</span>

<span class="co"># plot geographic coordinates of sites</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">sites</span><span class="op">$</span><span class="va">lon</span>, <span class="va">sites</span><span class="op">$</span><span class="va">lat</span>,
  col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/adjustcolor.html">adjustcolor</a></span><span class="op">(</span><span class="st">'grey'</span>,<span class="fl">0.4</span><span class="op">)</span>,
  pch <span class="op">=</span> <span class="fl">19</span>,
  cex<span class="op">=</span><span class="fl">0.3</span>
<span class="op">)</span></code></pre></div>
<p><img src="using_scca_files/figure-html/datainspectmap,-1.png" width="768"></p>
</div>
<div id="using-scca" class="section level2">
<h2 class="hasAnchor">
<a href="#using-scca" class="anchor"></a>Using SCCA</h2>
<p>Once familiar with the data we can now review the basic functions in the package. In this example, we apply Correspondence Analyses aiming to analyze sites according to their species composition (but we could have as well aimed at analyzing species based on their geographic distributions by applying the same procedure to columns instead of rows). The analysis yields a number of clusters in which data can be classified, and which are interpreted as bioregions.</p>
<div id="scca_compute-apply-ca-to-a-matrix-m" class="section level3">
<h3 class="hasAnchor">
<a href="#scca_compute-apply-ca-to-a-matrix-m" class="anchor"></a><code>scca_compute()</code>: apply CA to a matrix <em>m</em>
</h3>
<p>This function scca_compute performs a hierarchical, Spectral Clustering Correspondence Analysis on a matrix representing a bi-partite network. The proces consists of a decomposition of the matrix (svd), a (user-provided) heuristic which transforms the decompostion to input for kmeans clustering (k and the set of observations and, then, the kmeans clustering itself. Each of the resulting clusters (sub-matrices) can be analyzed again until some stopping condition is met. The output of sccs_compute is a tree (list of lists) in which every node represents one step in the process.</p>
<p><strong>Eijden: Mark suggested the following text to document scca_compute. It can also be used to replace the previous paragraph</strong></p>
<p>The function \emph{scca_compute} performs a hierarchical, Spectral Clustering Correspondence Analysis on a matrix M representing a bi-partite network. The process consists of the following steps:</p>
<ul>
<li>Computation of eigenvalues and eigenvectors of the similarity matrix derived from M.</li>
<li>Determine K, being how many relevant eigenvectors should be found.</li>
<li>Apply K-means to find a clustering of the elements of M into K clusters in a hierarchical manner.</li>
</ul>
<p>The function to calculate a number of clusters is a heuristic <em>eigengap_heuristic</em>, which inspects the eigenspectrum and finds the number of axis before the largest <em>eigengap</em> or distance between each axis and the next. <strong>Eijden: What about one eigenvalue with 1 one or several eigenvalues with value 1</strong></p>
<p>We can apply the function to the carnivora dataset, generate an object that we call <code>scca</code> and inspect the results using the function <code><a href="../reference/scca_print.html">scca_print()</a></code>.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="co"># application of this function to a large dataset sucha as the carnivora dataset here</span>
<span class="co"># can take up to a minute.</span>
<span class="va">scca</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/scca_compute.html">scca_compute</a></span><span class="op">(</span>m <span class="op">=</span> <span class="va">carnivora</span>, 
  iter.max <span class="op">=</span> <span class="fl">10</span>,
  nstart   <span class="op">=</span> <span class="fl">100</span>,
  disconnect.rm   <span class="op">=</span> <span class="cn">TRUE</span>,
  max_eigenvalues <span class="op">=</span> <span class="fl">25</span>,
  decomp    <span class="op">=</span> <span class="st">"svd"</span>,
  max_depth <span class="op">=</span> <span class="cn">Inf</span>,
  heuristic <span class="op">=</span> <span class="va">eigengap_heuristic</span><span class="op">)</span>

<span class="fu"><a href="../reference/scca_print.html">scca_print</a></span><span class="op">(</span><span class="va">scca</span> , <span class="st">'k'</span>, <span class="st">'n_labs'</span>, <span class="st">'depth'</span>, <span class="st">'node_type'</span><span class="op">)</span>
<span class="co">#&gt;         levelName  k n_labs depth node_type</span>
<span class="co">#&gt; 1  1               2  41579     1    branch</span>
<span class="co">#&gt; 2   ¦--2           1    127     2      leaf</span>
<span class="co">#&gt; 3   °--3          15  41452     2    branch</span>
<span class="co">#&gt; 4       ¦--4       1   1969     3      leaf</span>
<span class="co">#&gt; 5       ¦--5       1    896     3      leaf</span>
<span class="co">#&gt; 6       ¦--6       1   3208     3      leaf</span>
<span class="co">#&gt; 7       ¦--7       1   7922     3      leaf</span>
<span class="co">#&gt; 8       ¦--8       1     37     3      leaf</span>
<span class="co">#&gt; 9       ¦--9       1   8375     3      leaf</span>
<span class="co">#&gt; 10      ¦--10      1   1239     3      leaf</span>
<span class="co">#&gt; 11      ¦--11      2   1719     3    branch</span>
<span class="co">#&gt; 12      ¦   ¦--12  1    106     4      leaf</span>
<span class="co">#&gt; 13      ¦   °--13  1   1613     4      leaf</span>
<span class="co">#&gt; 14      ¦--14      1   1382     3      leaf</span>
<span class="co">#&gt; 15      ¦--15      1    449     3      leaf</span>
<span class="co">#&gt; 16      ¦--16      1   8242     3      leaf</span>
<span class="co">#&gt; 17      ¦--17      1     41     3      leaf</span>
<span class="co">#&gt; 18      ¦--18      1   1997     3      leaf</span>
<span class="co">#&gt; 19      ¦--19      1    125     3      leaf</span>
<span class="co">#&gt; 20      °--20      1   3851     3      leaf</span></code></pre></div>
</div>
<div id="scca_print-print-hierarchical-clustering" class="section level3">
<h3 class="hasAnchor">
<a href="#scca_print-print-hierarchical-clustering" class="anchor"></a><code>scca_print()</code>: print hierarchical clustering</h3>
<p>This function shows the hierarchical structure of fitted clusters.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="co">## inspect the structure of object scca</span>
<span class="fu"><a href="../reference/scca_print.html">scca_print</a></span><span class="op">(</span><span class="va">scca</span> , <span class="st">'k'</span>, <span class="st">'n_labs'</span>, <span class="st">'depth'</span>, <span class="st">'node_type'</span><span class="op">)</span>
<span class="co">#&gt;         levelName  k n_labs depth node_type</span>
<span class="co">#&gt; 1  1               2  41579     1    branch</span>
<span class="co">#&gt; 2   ¦--2           1    127     2      leaf</span>
<span class="co">#&gt; 3   °--3          15  41452     2    branch</span>
<span class="co">#&gt; 4       ¦--4       1   1969     3      leaf</span>
<span class="co">#&gt; 5       ¦--5       1    896     3      leaf</span>
<span class="co">#&gt; 6       ¦--6       1   3208     3      leaf</span>
<span class="co">#&gt; 7       ¦--7       1   7922     3      leaf</span>
<span class="co">#&gt; 8       ¦--8       1     37     3      leaf</span>
<span class="co">#&gt; 9       ¦--9       1   8375     3      leaf</span>
<span class="co">#&gt; 10      ¦--10      1   1239     3      leaf</span>
<span class="co">#&gt; 11      ¦--11      2   1719     3    branch</span>
<span class="co">#&gt; 12      ¦   ¦--12  1    106     4      leaf</span>
<span class="co">#&gt; 13      ¦   °--13  1   1613     4      leaf</span>
<span class="co">#&gt; 14      ¦--14      1   1382     3      leaf</span>
<span class="co">#&gt; 15      ¦--15      1    449     3      leaf</span>
<span class="co">#&gt; 16      ¦--16      1   8242     3      leaf</span>
<span class="co">#&gt; 17      ¦--17      1     41     3      leaf</span>
<span class="co">#&gt; 18      ¦--18      1   1997     3      leaf</span>
<span class="co">#&gt; 19      ¦--19      1    125     3      leaf</span>
<span class="co">#&gt; 20      °--20      1   3851     3      leaf</span></code></pre></div>
<p>There are 17 <em>leaf nodes</em> or clusters identified by the heuristic. <strong>Eijden: What about the stochastic nature? The number of clusters can differ per run of scca_compute. </strong></p>
<p>The attributes asked to be printed in <code><a href="../reference/scca_print.html">scca_print()</a></code> have the following meaning: <em>n_labs</em> is the number of observations (labels), <em>k</em> is the number of relevant Eigenvalues (i.e. before the eigengap) at each branch node, <em>node_type</em> is the type of branch (internal) or leaf (terminal) nodes. If no attribute is given, then only the tree hierarchy is printed.</p>
</div>
<div id="scca_get_clusters-retrieve-and-plotmap-clusters" class="section level3">
<h3 class="hasAnchor">
<a href="#scca_get_clusters-retrieve-and-plotmap-clusters" class="anchor"></a><code>scca_get_clusters()</code>: retrieve and plot/map clusters</h3>
<p>The function <code>scca_get_clusters</code> saves the observations and the cluster it has been assigned to, in an object. which allows to map obtained clusters or bioregions.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="co"># save the clusters in object scca</span>
<span class="op">(</span><span class="va">clusts</span><span class="op">&lt;-</span><span class="fu"><a href="../reference/scca_get_clusters.html">scca_get_clusters</a></span><span class="op">(</span><span class="va">scca</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 41,579 x 3</span>
<span class="co">#&gt;   label cluster path  </span>
<span class="co">#&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt; </span>
<span class="co">#&gt; 1 0          16 1.2.11</span>
<span class="co">#&gt; 2 1          16 1.2.11</span>
<span class="co">#&gt; 3 2          16 1.2.11</span>
<span class="co">#&gt; 4 3          16 1.2.11</span>
<span class="co">#&gt; # … with 41,575 more rows</span>

<span class="co">## how many clusters?</span>
<span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">clusts</span><span class="op">$</span><span class="va">cluster</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; [1] 17</span>


<span class="co"># plotting clusters</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">sites</span><span class="op">$</span><span class="va">lon</span>,<span class="va">sites</span><span class="op">$</span><span class="va">lat</span>,
     col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/adjustcolor.html">adjustcolor</a></span><span class="op">(</span><span class="st">'grey'</span>,<span class="fl">0.4</span><span class="op">)</span>,
     pch <span class="op">=</span> <span class="fl">19</span>,
     cex <span class="op">=</span> <span class="fl">0.3</span><span class="op">)</span>

<span class="kw">for</span><span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">clusts</span><span class="op">$</span><span class="va">cluster</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span><span class="co">#i=2</span>
  <span class="fu"><a href="https://rdrr.io/r/graphics/points.html">points</a></span><span class="op">(</span>
    <span class="va">sites</span><span class="op">$</span><span class="va">lon</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">clusts</span><span class="op">$</span><span class="va">cluster</span><span class="op">==</span><span class="va">i</span><span class="op">)</span><span class="op">]</span>,
    <span class="va">sites</span><span class="op">$</span><span class="va">lat</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">clusts</span><span class="op">$</span><span class="va">cluster</span><span class="op">==</span><span class="va">i</span><span class="op">)</span><span class="op">]</span>,
    pch <span class="op">=</span> <span class="fl">19</span>,
    cex <span class="op">=</span> <span class="fl">0.5</span>,
    col <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grDevices/adjustcolor.html">adjustcolor</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/grDevices/palettes.html">hcl.colors</a></span><span class="op">(</span><span class="fl">22</span><span class="op">)</span><span class="op">[</span><span class="va">i</span><span class="op">]</span>,<span class="fl">0.6</span><span class="op">)</span><span class="op">)</span>
<span class="op">}</span></code></pre></div>
<p><img src="using_scca_files/figure-html/saveplotclusters-1.png" width="768"></p>
<p>Regions shaded in different colors represent each cluster or bioregion. The loop above plots all clusters sequentially, but it would be easy to plot any single cluster by adjusting the range of values for <em>i</em>.</p>
</div>
</div>
<div id="scca_get_node-retrieve-any-given-node-axis-and-plot-its-eigen-spectrum" class="section level2">
<h2 class="hasAnchor">
<a href="#scca_get_node-retrieve-any-given-node-axis-and-plot-its-eigen-spectrum" class="anchor"></a><code>scca_get_node()</code>: retrieve any given node (axis) and plot its eigen-spectrum</h2>
<p>This function retrieves the values for any given node in object scca, which allows to, for example plot eigenspectrums. Type <code><a href="../reference/scca_get_node.html">?scca_get_node</a></code> at the R console to see which information is stored in a node. Not only for leaf nodes but also for bracnch nodes.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R">
<span class="va">node1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/scca_get_node.html">scca_get_node</a></span><span class="op">(</span><span class="va">scca</span>, node <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>

<span class="co">## check eigenvalues:</span>

<span class="co">## plot eigenspectrum</span>
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span>
  x <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">node1</span><span class="op">$</span><span class="va">spectrum</span><span class="op">)</span>,
  y <span class="op">=</span> <span class="va">node1</span><span class="op">$</span><span class="va">spectrum</span>,
  ylab <span class="op">=</span> <span class="st">"Eigenvalues"</span>,
  xlab <span class="op">=</span> <span class="st">"Index"</span><span class="op">)</span></code></pre></div>
<p><img src="using_scca_files/figure-html/spectralclust1-1.png" width="700"></p>
<p>There is however, a more direct function to plot the eigen spectrum for any given node: <code><a href="../reference/scca_plot_spectrum.html">scca_plot_spectrum()</a></code>.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">## the same can be done directly with function scca_plot_spectrum()</span>
<span class="fu"><a href="../reference/scca_plot_spectrum.html">scca_plot_spectrum</a></span><span class="op">(</span><span class="va">scca</span>,
  node <span class="op">=</span> <span class="fl">1</span>,
  plot <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<p><img src="using_scca_files/figure-html/spectralclust2-1.png" width="700"></p>
<pre><code>#&gt; # A tibble: 25 x 2
#&gt;   order value
#&gt;   &lt;int&gt; &lt;dbl&gt;
#&gt; 1     1 1.   
#&gt; 2     2 1.00 
#&gt; 3     3 0.986
#&gt; 4     4 0.951
#&gt; # … with 21 more rows</code></pre>
<p>These plots show the sorted spectrum for all data (node 1), showing two eigenvectors with value equal 1, indicating that there are two fully disconnected clusters. Function <code>scc_plot_spectrum()</code> also prints the sorted eigenvalues as a table.</p>
<div id="references" class="section level3">
<h3 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h3>
<p><a name="van_dam"> van Dam, Alje et al. (2021), <strong>Correspondence analysis, spectral clustering and graph embedding: applications to ecology and economic complexity</strong>; <em>name of journal</em>; DOI: <doi>. </doi></a></p>
<p><a name="faurby"> Faurby, Søren et al. (2019), Data from: PHYLACINE 1.2: The Phylogenetic Atlas of Mammal Macroecology, Dryad, Dataset, [</a><a href="https://doi.org/10.5061/dryad.bp26v20" class="uri">https://doi.org/10.5061/dryad.bp26v20</a>] </p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Alje van Dam, Mark Dekker, Kees van Eijden.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
